"""
Export all project Python source into one text file for review / submission.
Run from the repo root:  python export_code.py
"""
import os

# Directories and root-level files to include (relative to repo root)
TARGET_PATHS = [
    # --- packages ---
    "./agent",
    "./app_platform",
    "./context_eval",
    "./db",
    "./mcp_server",
    "./memory",
    "./multi_agent",
    "./planning",
    "./planning_eval",
    "./platform_db",
    "./rag",
    "./retrieval_eval",
    "./state_graph",
    # --- root scripts ---
    "./demo_all.py",
    "./demo_final.py",
    "./export_code.py",
]

# Skip noise inside packages
SKIP_DIR_NAMES = {
    "__pycache__",
    ".git",
    "venv",
    ".venv",
    "node_modules",
    "Lib",
    "site-packages",
    "IronBridge-Memory-Project",
    "index",
    "corpus",  # markdown corpus, not code
}

OUTPUT_FILE = "full_code.txt"


def should_skip_dir(dirname: str) -> bool:
    return dirname in SKIP_DIR_NAMES or dirname.endswith(".egg-info")


def export_code() -> None:
    exported_count = 0
    with open(OUTPUT_FILE, "w", encoding="utf-8") as outfile:
        outfile.write("# Iron Bridge Construction — full Python source export\n")
        outfile.write("# Generated by export_code.py\n\n")

        for target in TARGET_PATHS:
            target = os.path.normpath(target)
            if os.path.isfile(target):
                if target.endswith(".py"):
                    write_file_to_txt(target, outfile)
                    exported_count += 1
            elif os.path.isdir(target):
                for root, dirs, files in os.walk(target):
                    # prune in-place so os.walk does not descend
                    dirs[:] = [d for d in dirs if not should_skip_dir(d)]
                    for file in sorted(files):
                        if not file.endswith(".py"):
                            continue
                        file_path = os.path.join(root, file)
                        write_file_to_txt(file_path, outfile)
                        exported_count += 1
            else:
                print(f"⚠️  Skipped (not found): {target}")

    print(f"\n✅ Successfully exported {exported_count} Python files to '{OUTPUT_FILE}'!")


def write_file_to_txt(file_path: str, outfile) -> None:
    # Pretty relative path with forward slashes
    normalized = os.path.normpath(file_path).replace("\\", "/")
    if not normalized.startswith("./"):
        normalized = "./" + normalized.lstrip("/")

    try:
        with open(file_path, "r", encoding="utf-8") as infile:
            code_content = infile.read()

        outfile.write(f"file({normalized}):\n")
        outfile.write("-" * 40 + "\n")
        outfile.write(code_content)
        if not code_content.endswith("\n"):
            outfile.write("\n")
        outfile.write("=" * 40 + "\n\n")
        print(f"📄 Added: {normalized}")
    except Exception as e:
        print(f"❌ Error reading {file_path}: {e}")


if __name__ == "__main__":
    export_code()
